#!/usr/bin/env python3
"""Emit the installed Lumen cross-talk candidate tables as a Phoenix C++ source.

Fails closed: every table is SHA-256 verified against the digests proven in
verify_crosstalk_amount_formula.py before a single byte is emitted, and libcp
itself is verified against the pinned image hash by verify_static().

Output: engine/depth/cross_talk_tables.cpp  (+ matching .h)
"""

from __future__ import annotations

import hashlib
import importlib.util
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
HERE = Path(__file__).resolve().parent
PHOENIX = Path("/Users/ryaker/L16_Phoenix/phoenix")


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


AMOUNT = load_module("ct_amount", HERE / "verify_crosstalk_amount_formula.py")
STATIC = AMOUNT.STATIC
TABLE_BYTES = AMOUNT.TABLE_BYTES
WORDS = TABLE_BYTES // 4
FIT_W = AMOUNT.FIT_WIDTH
FIT_H = AMOUNT.FIT_HEIGHT


def hex_f32(raw: bytes, index: int) -> tuple[float, int]:
    word = struct.unpack_from("<I", raw, index * 4)[0]
    value = struct.unpack_from("<f", raw, index * 4)[0]
    return value, word


def emit_table(out, name: str, raw: bytes) -> None:
    out.append(f"const float {name}[{WORDS}] = {{")
    line = "   "
    for i in range(WORDS):
        value, word = hex_f32(raw, i)
        # exact hexadecimal float literal: no decimal round-trip risk
        assert value == value and abs(value) != float("inf"), f"{name}[{i}] not finite"
        text = f" {float(value).hex()}f,"
        if len(line) + len(text) > 96:
            out.append(line)
            line = "   "
        line += text
    if line.strip():
        out.append(line)
    out.append("};")
    out.append("")


def main() -> None:
    data, mapping = AMOUNT.verify_static()
    print("libcp verified; all table digests match")

    tables: list[tuple[str, bytes]] = []
    for name, (base, hashes) in sorted(AMOUNT.TABLES.items()):
        for group, expected in enumerate(hashes):
            raw = STATIC.bytes_at(data, mapping, base + group * TABLE_BYTES, TABLE_BYTES)
            digest = hashlib.sha256(raw).hexdigest()
            assert digest == expected, f"{name}[{group}] digest drift"
            tables.append((f"kCrossTalk_{name}_g{group}", raw))
    for name, (address, expected) in sorted(AMOUNT.SENSOR4_TABLES.items()):
        raw = STATIC.bytes_at(data, mapping, address, TABLE_BYTES)
        digest = hashlib.sha256(raw).hexdigest()
        assert digest == expected, f"{name}_sensor4 digest drift"
        tables.append((f"kCrossTalk_{name}_sensor4", raw))

    print(f"emitting {len(tables)} tables x {WORDS} f32 words")

    lines: list[str] = []
    lines.append("// GENERATED by tools/lldb_probes/correction_liveness/emit_crosstalk_tables_cpp.py")
    lines.append("// Source: Lumen libcp.dylib SHA-256")
    lines.append(f"//   {AMOUNT.LIBCP_SHA256}")
    lines.append("// Each table is a 17x13 grid of 4-lane cross-talk candidates (row-major, y outer).")
    lines.append("// Selection: letter A/B/C, sensor selector (1/2 -> variant+group, 4 -> single),")
    lines.append("// variant flag, camera group (0: id<=4, 1: id<=9, 2: id<=15).")
    lines.append("// Do not edit by hand.")
    lines.append("")
    lines.append('#include "cross_talk_tables.h"')
    lines.append("")
    lines.append("namespace phoenix {")
    lines.append("namespace crosstalk {")
    lines.append("namespace {")
    lines.append("")
    for name, raw in tables:
        emit_table(lines, name, raw)
    lines.append("}  // namespace")
    lines.append("")

    # selector
    lines.append("const float* candidateTable(char letter, int sensor, bool variant, int group) {")
    lines.append("  if (sensor == 4) {")
    lines.append("    switch (letter) {")
    for letter in ("A", "B", "C"):
        lines.append(f"      case '{letter}': return kCrossTalk_{letter}_sensor4;")
    lines.append("      default: return nullptr;")
    lines.append("    }")
    lines.append("  }")
    lines.append("  if (group < 0 || group > 2) return nullptr;")
    lines.append("  switch (letter) {")
    for letter in ("A", "B", "C"):
        lines.append(f"    case '{letter}':")
        lines.append("      if (variant) {")
        lines.append(f"        static const float* const kT[3] = {{kCrossTalk_{letter}_true_g0, "
                     f"kCrossTalk_{letter}_true_g1, kCrossTalk_{letter}_true_g2}};")
        lines.append("        return kT[group];")
        lines.append("      } else {")
        lines.append(f"        static const float* const kF[3] = {{kCrossTalk_{letter}_false_g0, "
                     f"kCrossTalk_{letter}_false_g1, kCrossTalk_{letter}_false_g2}};")
        lines.append("        return kF[group];")
        lines.append("      }")
    lines.append("    default: return nullptr;")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("}  // namespace crosstalk")
    lines.append("}  // namespace phoenix")
    lines.append("")

    dest = PHOENIX / "engine/depth/cross_talk_tables.cpp"
    dest.write_text("\n".join(lines))
    print("wrote", dest, dest.stat().st_size, "bytes")

    header = [
        "// GENERATED companion header for cross_talk_tables.cpp. Do not edit by hand.",
        "#pragma once",
        "",
        "namespace phoenix {",
        "namespace crosstalk {",
        "",
        f"constexpr int kFitWidth = {FIT_W};",
        f"constexpr int kFitHeight = {FIT_H};",
        f"constexpr int kFitWords = {WORDS};  // kFitWidth * kFitHeight * 4",
        "",
        "// letter: 'A' | 'B' | 'C'.  sensor: 1, 2 (grouped) or 4 (single).",
        "// Returns a kFitWords-long row-major (y, x, lane) array, or nullptr if unsupported.",
        "const float* candidateTable(char letter, int sensor, bool variant, int group);",
        "",
        "}  // namespace crosstalk",
        "}  // namespace phoenix",
        "",
    ]
    hdest = PHOENIX / "engine/depth/cross_talk_tables.h"
    hdest.write_text("\n".join(header))
    print("wrote", hdest, hdest.stat().st_size, "bytes")


if __name__ == "__main__":
    main()
